[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
clap = "3.1.*"
regex = "1.5.*"
serde = "1.*"
serde_json = "1.*"
serde_derive = "1.*"
chrono = "0.4.*"

[[bin]]
name = "aoc"
path = "src/main.rs"